name: doc

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        sudo apt install -y doxygen virtualenv npm
        sudo npm install -g less clean-css
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=Release $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --target doc --config Release

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: HTML documentation
        path: |
          ${{runner.workspace}}/build/doc/html
          !${{runner.workspace}}/build/doc/html/.doctrees
